name: cryptotool
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  analyzer: ^0.39.17
  
  dio: ^3.0.10
  retrofit: ^1.3.4
  json_annotation: ^3.1.0
  # comment logger and alice when release bundle
  logger: ^0.9.4
  # alice: ^0.1.5
  #pretty_dio_logger: ^1.1.0

  injector: ^1.0.9

  rxdart: ^0.24.1

  intl: ^0.16.1

  dartx: ^0.5.0

  shared_preferences: ^0.5.12+2

  pull_to_refresh: ^1.6.2

  equatable: ^1.2.5
  flutter_bloc: ^6.1.0

  url_launcher: ^5.7.8

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.3.8+2
  build_runner: ^1.10.2
  json_serializable: ^3.5.0
  flutter_launcher_icons: ^0.8.0
  flutter_native_splash: ^0.1.9

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg